import { EDGE_FORMAT, PositionStyle, VERTICAL_SPACING } from "./types_style";

export const _DEFAULT_POSITIONSTYLE: PositionStyle = {
    VERTICAL_SPACING: VERTICAL_SPACING.centered,
    SHOW_TILES: true,
    EDGE_TO_EDGE_VERTICAL_GAP: 12,
    EDGE_TO_EDGE_HORIZONTAL_GAP: 12,
    JOIN_MARGIN: 7.5, // = NodeBorderRadius + (EdgeWidth / 2)
    COLLAPSE_BUFFER: 7, // = (EdgeWidth * 2) + 1
    NODE_VERTICAL_GAP: 33,
    EDGE_FORMAT: EDGE_FORMAT.classic,
    EDGE_SMOOTHING: 20, // 20
    TILE_VERTICAL_PADDING: 15,
    TILE_HORIZONTAL_PADDING: 15,
    TILE_HORIZONTAL_GAP: 10,
};
